import type { Metadata } from 'next'
import { ReactNode } from 'react'

import './globals.css'

export const metadata: Metadata = {
  title: 'Electron Example',
  description: 'Generated by create next app',
}

interface RootLayoutProps {
  children: ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="antialiased select-none bg-zinc-900 text-zinc-50">
        {children}
      </body>
    </html>
  )
}
